(function(root){
  // Stable URL slugs: independent of browser locale and display-name updates.
  const slugs={
  "AF": "afghanistan",
  "AL": "albania",
  "DZ": "algeria",
  "AD": "andorra",
  "AO": "angola",
  "AG": "antigua-and-barbuda",
  "AR": "argentina",
  "AM": "armenia",
  "AU": "australia",
  "AT": "austria",
  "AZ": "azerbaijan",
  "BS": "bahamas",
  "BH": "bahrain",
  "BD": "bangladesh",
  "BB": "barbados",
  "BY": "belarus",
  "BE": "belgium",
  "BZ": "belize",
  "BJ": "benin",
  "BT": "bhutan",
  "BO": "bolivia",
  "BA": "bosnia-and-herzegovina",
  "BW": "botswana",
  "BR": "brazil",
  "BN": "brunei",
  "BG": "bulgaria",
  "BF": "burkina-faso",
  "BI": "burundi",
  "KH": "cambodia",
  "CM": "cameroon",
  "CA": "canada",
  "CV": "cape-verde",
  "CF": "central-african-republic",
  "TD": "chad",
  "CL": "chile",
  "CN": "china",
  "CO": "colombia",
  "KM": "comoros",
  "CR": "costa-rica",
  "CI": "cote-d-ivoire",
  "HR": "croatia",
  "CU": "cuba",
  "CY": "cyprus",
  "CZ": "czech-republic",
  "CD": "democratic-republic-of-the-congo",
  "DK": "denmark",
  "DJ": "djibouti",
  "DM": "dominica",
  "DO": "dominican-republic",
  "EC": "ecuador",
  "EG": "egypt",
  "SV": "el-salvador",
  "GQ": "equatorial-guinea",
  "ER": "eritrea",
  "EE": "estonia",
  "SZ": "eswatini",
  "ET": "ethiopia",
  "FJ": "fiji",
  "FI": "finland",
  "FR": "france",
  "GA": "gabon",
  "GM": "gambia",
  "GE": "georgia",
  "DE": "germany",
  "GH": "ghana",
  "GR": "greece",
  "GD": "grenada",
  "GT": "guatemala",
  "GN": "guinea",
  "GW": "guinea-bissau",
  "GY": "guyana",
  "HT": "haiti",
  "HN": "honduras",
  "HU": "hungary",
  "IS": "iceland",
  "IN": "india",
  "ID": "indonesia",
  "IR": "iran",
  "IQ": "iraq",
  "IE": "ireland",
  "IL": "israel",
  "IT": "italy",
  "JM": "jamaica",
  "JP": "japan",
  "JO": "jordan",
  "KZ": "kazakhstan",
  "KE": "kenya",
  "KI": "kiribati",
  "XK": "kosovo",
  "KW": "kuwait",
  "KG": "kyrgyzstan",
  "LA": "laos",
  "LV": "latvia",
  "LB": "lebanon",
  "LS": "lesotho",
  "LR": "liberia",
  "LY": "libya",
  "LI": "liechtenstein",
  "LT": "lithuania",
  "LU": "luxembourg",
  "MG": "madagascar",
  "MW": "malawi",
  "MY": "malaysia",
  "MV": "maldives",
  "ML": "mali",
  "MT": "malta",
  "MH": "marshall-islands",
  "MR": "mauritania",
  "MU": "mauritius",
  "MX": "mexico",
  "FM": "micronesia",
  "MD": "moldova",
  "MC": "monaco",
  "MN": "mongolia",
  "ME": "montenegro",
  "MA": "morocco",
  "MZ": "mozambique",
  "MM": "myanmar-burma",
  "NA": "namibia",
  "NR": "nauru",
  "NP": "nepal",
  "NL": "netherlands",
  "NZ": "new-zealand",
  "NI": "nicaragua",
  "NE": "niger",
  "NG": "nigeria",
  "KP": "north-korea",
  "MK": "north-macedonia",
  "NO": "norway",
  "OM": "oman",
  "PK": "pakistan",
  "PW": "palau",
  "PS": "palestine",
  "PA": "panama",
  "PG": "papua-new-guinea",
  "PY": "paraguay",
  "PE": "peru",
  "PH": "philippines",
  "PL": "poland",
  "PT": "portugal",
  "QA": "qatar",
  "CG": "republic-of-the-congo",
  "RO": "romania",
  "RU": "russia",
  "RW": "rwanda",
  "WS": "samoa",
  "SM": "san-marino",
  "ST": "sao-tome-and-principe",
  "SA": "saudi-arabia",
  "SN": "senegal",
  "RS": "serbia",
  "SC": "seychelles",
  "SL": "sierra-leone",
  "SG": "singapore",
  "SK": "slovakia",
  "SI": "slovenia",
  "SB": "solomon-islands",
  "SO": "somalia",
  "ZA": "south-africa",
  "KR": "south-korea",
  "SS": "south-sudan",
  "ES": "spain",
  "LK": "sri-lanka",
  "KN": "st-kitts-and-nevis",
  "LC": "st-lucia",
  "VC": "st-vincent-and-grenadines",
  "SD": "sudan",
  "SR": "suriname",
  "SE": "sweden",
  "CH": "switzerland",
  "SY": "syria",
  "TW": "taiwan",
  "TJ": "tajikistan",
  "TZ": "tanzania",
  "TH": "thailand",
  "TL": "timor-leste",
  "TG": "togo",
  "TO": "tonga",
  "TT": "trinidad-and-tobago",
  "TN": "tunisia",
  "TR": "turkey",
  "TM": "turkmenistan",
  "TV": "tuvalu",
  "UG": "uganda",
  "UA": "ukraine",
  "AE": "united-arab-emirates",
  "GB": "united-kingdom",
  "US": "united-states",
  "UY": "uruguay",
  "UZ": "uzbekistan",
  "VU": "vanuatu",
  "VA": "vatican-city",
  "VE": "venezuela",
  "VN": "vietnam",
  "EH": "western-sahara",
  "YE": "yemen",
  "ZM": "zambia",
  "ZW": "zimbabwe"
};
  const regionCodes={
    'Europe':'AL AD AT BY BE BA BG HR CY CZ DK EE FI FR DE GR HU IS IE IT XK LV LI LT LU MT MD MC ME NL MK NO PL PT RO RU SM RS SK SI ES SE CH TR UA GB VA'.split(' '),
    'Americas':'AG AR BS BB BZ BO BR CA CL CO CR CU DM DO EC SV GD GT GY HT HN JM MX NI PA PY PE KN LC VC SR TT US UY VE'.split(' '),
    'Middle East & North Africa':'DZ BH EG EH IR IQ IL JO KW LB LY MR MA OM PS QA SA SD SY TN AE YE'.split(' '),
    'Sub-Saharan Africa':'AO BJ BW BF BI CV CM CF TD KM CD CG CI DJ GQ ER SZ ET GA GM GH GN GW KE LS LR MG MW ML MU MZ NA NE NG RW ST SN SC SL SO ZA SS TZ TG UG ZM ZW'.split(' '),
    'Asia-Pacific':'AF AM AZ AU BD BT BN KH CN FJ GE IN ID JP KZ KI KP KR KG LA MY MV MH FM MN MM NR NP NZ PK PW PG PH WS SG SB LK TW TJ TH TL TO TM TV UZ VU VN'.split(' ')
  };
  const nameOverrides={
    BO:'Bolivia',BN:'Brunei',CD:'Democratic Republic of the Congo',CG:'Republic of the Congo',CI:"Côte d’Ivoire",CV:'Cape Verde',
    CZ:'Czech Republic',EH:'Western Sahara',FM:'Micronesia',GB:'United Kingdom',IR:'Iran',KR:'South Korea',KP:'North Korea',
    LA:'Laos',MD:'Moldova',MK:'North Macedonia',PS:'Palestine',RU:'Russia',ST:'São Tomé and Príncipe',SY:'Syria',
    SZ:'Eswatini',TW:'Taiwan',TZ:'Tanzania',US:'United States',VA:'Vatican City',VE:'Venezuela',VN:'Vietnam',XK:'Kosovo'
  };
  const displayNames=typeof Intl!=='undefined'&&Intl.DisplayNames?new Intl.DisplayNames(['en'],{type:'region'}):null;
  const flag=code=>`/flags/${code.toLowerCase()}.svg`;
  const countries=[];
  Object.entries(regionCodes).forEach(([region,codes])=>codes.forEach(code=>countries.push({
    code,
    slug:slugs[code],
    name:nameOverrides[code]||(displayNames?displayNames.of(code):code),
    region,
    flag:flag(code)
  })));
  countries.sort((a,b)=>a.name.localeCompare(b.name,'en'));
  root.DEADLINE_COUNTRIES=countries;
  if(typeof module!=='undefined'&&module.exports)module.exports=countries;
})(typeof window!=='undefined'?window:globalThis);
